# This workflow will build / test & public the projects in the solution file

name: Build, Test & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        path: main
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Check TECH COOL
      run: git clone https://github.com/permadsenaalborg2/TECHCOOL_YET_ANOTHER_FORK
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: main
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: main
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: main

    - name: Publish
      run: dotnet publish
      working-directory: main

    - name: Build the Docker image
      run: docker build . --file main/Adventure.dockerfile --tag ghcr.io/permadsenaalborg2/adventuregame

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker image
      run: docker push ghcr.io/permadsenaalborg2/adventuregame

    # Use this for debug
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
